
package code39.net.webservicex;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BarCode", targetNamespace = "http://www.webserviceX.NET", wsdlLocation = "http://www.webservicex.net/barcode.asmx?WSDL")
public class BarCode
    extends Service
{

    private final static URL BARCODE_WSDL_LOCATION;
    private final static WebServiceException BARCODE_EXCEPTION;
    private final static QName BARCODE_QNAME = new QName("http://www.webserviceX.NET", "BarCode");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://www.webservicex.net/barcode.asmx?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BARCODE_WSDL_LOCATION = url;
        BARCODE_EXCEPTION = e;
    }

    public BarCode() {
        super(__getWsdlLocation(), BARCODE_QNAME);
    }

    public BarCode(WebServiceFeature... features) {
        super(__getWsdlLocation(), BARCODE_QNAME, features);
    }

    public BarCode(URL wsdlLocation) {
        super(wsdlLocation, BARCODE_QNAME);
    }

    public BarCode(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BARCODE_QNAME, features);
    }

    public BarCode(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BarCode(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BarCodeSoap
     */
    @WebEndpoint(name = "BarCodeSoap")
    public BarCodeSoap getBarCodeSoap() {
        return super.getPort(new QName("http://www.webserviceX.NET", "BarCodeSoap"), BarCodeSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BarCodeSoap
     */
    @WebEndpoint(name = "BarCodeSoap")
    public BarCodeSoap getBarCodeSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.webserviceX.NET", "BarCodeSoap"), BarCodeSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BARCODE_EXCEPTION!= null) {
            throw BARCODE_EXCEPTION;
        }
        return BARCODE_WSDL_LOCATION;
    }

}
