
package code39.net.webservicex;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BarCodeSoap", targetNamespace = "http://www.webserviceX.NET")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BarCodeSoap {


    /**
     * BARCODE Generator for CODE39.This is 3 of 9 (sometimes called code 39), a widely used barcode standard that includes capital letters, numbers, and several symbols
     * 
     * @param title
     * @param showCodeString
     * @param code
     * @param barSize
     * @return
     *     returns byte[]
     */
    @WebMethod(operationName = "Code39", action = "http://www.webserviceX.NET/Code39")
    @WebResult(name = "Code39Result", targetNamespace = "http://www.webserviceX.NET")
    @RequestWrapper(localName = "Code39", targetNamespace = "http://www.webserviceX.NET", className = "net.webservicex.Code39")
    @ResponseWrapper(localName = "Code39Response", targetNamespace = "http://www.webserviceX.NET", className = "net.webservicex.Code39Response")
    public byte[] code39(
        @WebParam(name = "Code", targetNamespace = "http://www.webserviceX.NET")
        String code,
        @WebParam(name = "BarSize", targetNamespace = "http://www.webserviceX.NET")
        int barSize,
        @WebParam(name = "ShowCodeString", targetNamespace = "http://www.webserviceX.NET")
        boolean showCodeString,
        @WebParam(name = "Title", targetNamespace = "http://www.webserviceX.NET")
        String title);

}
