
package unspc.net.webservicex;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "GenericUNSPSCSoap", targetNamespace = "http://www.webservicex.net/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GenericUNSPSCSoap {


    /**
     * Get UNSPSC Segment details
     * 
     * @param unspscSegmentData
     * @param getUNSPSCSegmentsResult
     */
    @WebMethod(operationName = "GetUNSPSCSegments", action = "http://www.webservicex.net/GetUNSPSCSegments")
    @RequestWrapper(localName = "GetUNSPSCSegments", targetNamespace = "http://www.webservicex.net/", className = "net.webservicex.GetUNSPSCSegments")
    @ResponseWrapper(localName = "GetUNSPSCSegmentsResponse", targetNamespace = "http://www.webservicex.net/", className = "net.webservicex.GetUNSPSCSegmentsResponse")
    public void getUNSPSCSegments(
        @WebParam(name = "GetUNSPSCSegmentsResult", targetNamespace = "http://www.webservicex.net/", mode = WebParam.Mode.OUT)
        Holder<Boolean> getUNSPSCSegmentsResult,
        @WebParam(name = "UNSPSCSegmentData", targetNamespace = "http://www.webservicex.net/", mode = WebParam.Mode.OUT)
        Holder<UNSPSCSegmentList> unspscSegmentData);

    /**
     * Get UNSPSC Family details by Segment
     * 
     * @param getUNSPSCFamilyBySegmentResult
     * @param segment
     * @param unspscFamilyData
     */
    @WebMethod(operationName = "GetUNSPSCFamilyBySegment", action = "http://www.webservicex.net/GetUNSPSCFamilyBySegment")
    @RequestWrapper(localName = "GetUNSPSCFamilyBySegment", targetNamespace = "http://www.webservicex.net/", className = "net.webservicex.GetUNSPSCFamilyBySegment")
    @ResponseWrapper(localName = "GetUNSPSCFamilyBySegmentResponse", targetNamespace = "http://www.webservicex.net/", className = "net.webservicex.GetUNSPSCFamilyBySegmentResponse")
    public void getUNSPSCFamilyBySegment(
        @WebParam(name = "Segment", targetNamespace = "http://www.webservicex.net/")
        String segment,
        @WebParam(name = "GetUNSPSCFamilyBySegmentResult", targetNamespace = "http://www.webservicex.net/", mode = WebParam.Mode.OUT)
        Holder<Boolean> getUNSPSCFamilyBySegmentResult,
        @WebParam(name = "UNSPSCFamilyData", targetNamespace = "http://www.webservicex.net/", mode = WebParam.Mode.OUT)
        Holder<UNSPSCFamilyList> unspscFamilyData);

    /**
     * Get UNSPSC Family details by Family
     * 
     * @param getUNSPSCClassByFamilyResult
     * @param family
     * @param unspscClassData
     */
    @WebMethod(operationName = "GetUNSPSCClassByFamily", action = "http://www.webservicex.net/GetUNSPSCClassByFamily")
    @RequestWrapper(localName = "GetUNSPSCClassByFamily", targetNamespace = "http://www.webservicex.net/", className = "net.webservicex.GetUNSPSCClassByFamily")
    @ResponseWrapper(localName = "GetUNSPSCClassByFamilyResponse", targetNamespace = "http://www.webservicex.net/", className = "net.webservicex.GetUNSPSCClassByFamilyResponse")
    public void getUNSPSCClassByFamily(
        @WebParam(name = "Family", targetNamespace = "http://www.webservicex.net/")
        String family,
        @WebParam(name = "GetUNSPSCClassByFamilyResult", targetNamespace = "http://www.webservicex.net/", mode = WebParam.Mode.OUT)
        Holder<Boolean> getUNSPSCClassByFamilyResult,
        @WebParam(name = "UNSPSCClassData", targetNamespace = "http://www.webservicex.net/", mode = WebParam.Mode.OUT)
        Holder<UNSPSCClassList> unspscClassData);

    /**
     * Get UNSPSC Commodity details by Class
     * 
     * @param _class
     * @param unspscCommodityData
     * @param getUNSPSCCommodityByClassResult
     */
    @WebMethod(operationName = "GetUNSPSCCommodityByClass", action = "http://www.webservicex.net/GetUNSPSCCommodityByClass")
    @RequestWrapper(localName = "GetUNSPSCCommodityByClass", targetNamespace = "http://www.webservicex.net/", className = "net.webservicex.GetUNSPSCCommodityByClass")
    @ResponseWrapper(localName = "GetUNSPSCCommodityByClassResponse", targetNamespace = "http://www.webservicex.net/", className = "net.webservicex.GetUNSPSCCommodityByClassResponse")
    public void getUNSPSCCommodityByClass(
        @WebParam(name = "Class", targetNamespace = "http://www.webservicex.net/")
        String _class,
        @WebParam(name = "GetUNSPSCCommodityByClassResult", targetNamespace = "http://www.webservicex.net/", mode = WebParam.Mode.OUT)
        Holder<Boolean> getUNSPSCCommodityByClassResult,
        @WebParam(name = "UNSPSCCommodityData", targetNamespace = "http://www.webservicex.net/", mode = WebParam.Mode.OUT)
        Holder<UNSPSCCommodityList> unspscCommodityData);

    /**
     * Get UNSPSC Commodity details by Commodity Title
     * 
     * @param commodityTitle
     * @param getUNSPSCByCommodityByTitleResult
     * @param unspscCommodityData
     */
    @WebMethod(operationName = "GetUNSPSCByCommodityByTitle", action = "http://www.webservicex.net/GetUNSPSCByCommodityByTitle")
    @RequestWrapper(localName = "GetUNSPSCByCommodityByTitle", targetNamespace = "http://www.webservicex.net/", className = "net.webservicex.GetUNSPSCByCommodityByTitle")
    @ResponseWrapper(localName = "GetUNSPSCByCommodityByTitleResponse", targetNamespace = "http://www.webservicex.net/", className = "net.webservicex.GetUNSPSCByCommodityByTitleResponse")
    public void getUNSPSCByCommodityByTitle(
        @WebParam(name = "CommodityTitle", targetNamespace = "http://www.webservicex.net/")
        String commodityTitle,
        @WebParam(name = "GetUNSPSCByCommodityByTitleResult", targetNamespace = "http://www.webservicex.net/", mode = WebParam.Mode.OUT)
        Holder<Boolean> getUNSPSCByCommodityByTitleResult,
        @WebParam(name = "UNSPSCCommodityData", targetNamespace = "http://www.webservicex.net/", mode = WebParam.Mode.OUT)
        Holder<UNSPSCCommodityList> unspscCommodityData);

}
